### ISSUE TITLE
1つのゲームに対してPlatformは複数持てるようにテーブル設計を見直す

### ISSUE THREAD

**Issue by yoshi-koyama** [renangton/task5_crud_read_and_create#3]
# 概要
素晴らしい完成度ですね。
とくにREADME.mdがとても見やすくレビューしやすいです。

仕様面で1つリクエストがあります。

1つのゲームに対して複数のプラットフォームを持てるようにしましょう。

platformテーブルが必要になります。
それからgamesとplatformの関係は多対多になります。

少々複雑なテーブル設計が必要なので以下の順で実施していきましょう。

- 多対多のテーブル設計について学ぶ
- create table文を作成してレビュー依頼する
  - 作成したテーブル（game、platform、中間テーブルの3つになるはず）
- 以下のような結果が取れるSQL文をjoinを使って書く

|id|game|platform|その他のカラム|
|---|---|---|---|
|1| WITCHER3 |PS4|...|
|1| WITCHER3 |Steam|...|
|1| WITCHER3 |Switch|...|
|2|...|...|...|

- 画面にPlatformをどのように表示するのかを検討する

【案】

|id|game|platform|その他のカラム|
|---|---|---|---|
|1| WITCHER3 |PS4/Steam/Switch|...|
|2|...|...|...|

Metacriticなどゲームを紹介するサイトを参考にしてみるのもいいと思います。

- 作成したテーブルからゲーム一覧に表示したい情報が取れるようなSQLまたはJavaコードを実装する

# 留意事項
- 一旦Platformごとの値段は同じとする

# 完了の定義
- [x] テーブル設計が見直しされていること
- [x] docker-compose up時のデータベース初期データの登録が新しいテーブル定義に合わせて修正されていること
- [x] 画面にゲーム一覧を表示するときに対応するすべてのプラットフォームが表示されるように実装が修正されていること
- [x] README.mdが更新されていること

# 参考
多対多、Many to manyなどで検索するとよいです
https://qiita.com/ramuneru/items/db43589551dd0c00fef9

**Comment by renangton** [comment]
@yoshi-koyama 
# 概要

テーブル設計を見直し、create文を編集しました。
6ceb9b66e618e2ed1c180a5d8261c280f82f6aad

# 申し送り事項

CREATE TABLE文のレビューをお願いします。

# 参考資料

https://qiita.com/ramuneru/items/db43589551dd0c00fef9
https://www.dbonline.jp/mysql/join/index1.html
https://dev.mysql.com/doc/refman/5.6/ja/create-table-foreign-keys.html

# SELECT文結果

![select](https://user-images.githubusercontent.com/97335620/154827300-1681be61-f68b-492e-84f8-efa7d6e64398.png)

**Comment by yoshi-koyama** [comment]
@renangton 
下記コミットにコメントしました！
https://github.com/renangton/task5_crud_read_and_create/commit/6ceb9b66e618e2ed1c180a5d8261c280f82f6aad

たとえばWitcher3のような複数のプラットフォームでプレイできるようなゲームのデータを登録して期待通り結果が出力されているか確認してほしいです！
<img width="529" alt="スクリーンショット 2022-02-20 12 40 30" src="https://user-images.githubusercontent.com/62045457/154827530-0f1b7e87-c7fa-4ca6-a8f7-e43e9aa8db31.png">

**Comment by renangton** [comment]
@yoshi-koyama 
下記コミットの方に返信しました。
https://github.com/renangton/task5_crud_read_and_create/commit/6ceb9b66e618e2ed1c180a5d8261c280f82f6aad#r67064708
Witcher3に複数のプラットフォームを登録し、出力してみました。
idにgames.idの方を使用していますが、問題ありませんでしょうか？

![witcher3](https://user-images.githubusercontent.com/97335620/154828576-459d7df3-19d2-4a58-98c7-c5d82f8c0a60.png)

**Comment by yoshi-koyama** [comment]
@renangton 
> idにgames.idの方を使用していますが、問題ありませんでしょうか？

これはSQLをどう出したいかによりますが、レナトさんのようにgp.idはあくまでも中間テーブルなので私でしたら、同じくg.idで良いと思います。

SELECT g.id as game_id ...
SQLの場合に限り、カラム名をより明確にするかと思います。

Javaコードの場合、Gameクラスのidであればgameのidだとすぐわかりますが、SQLだと何のIDか明確にしておくほうが親切かと思います。

**Comment by yoshi-koyama** [comment]
@renangton 
あとは念の為の動作確認として
- 1つもGameが紐付かないPlatformは出力されないこと
- 1つもPlatformが紐付かないGameは出力されないこと
の確認をしましょう。

**Comment by renangton** [comment]
完了
