### ISSUE TITLE
値段は3桁ごとにカンマを入れるようにする

### ISSUE THREAD

**Issue by yoshi-koyama** [renangton/task5_crud_read_and_create#7]
# 概要

画面表示するときにpriceにカンマを入れるようにしましょう。

前：1000
後：1,000

現状GameServiceから返却されたGameクラスをそのまま画面表示に使っていると思いますが、新しくGameViewクラスをつくりpriceは文字列として扱うのがいいかとおもいます。

こんなイメージです。

┣ controller
┃└ GameController
┣ entity
┃└Game
┣ form
┃└GameForm
┣ view
┃└GameView
...

#3 の対応次第ではこのあたりの構造も変わるかもしれませんね。

# 完了の定義
- [x] 値段が3桁ごとのカンマ区切りで画面に表示されること

# 参考資料

英語で調べてもいいですが「数字 3桁 java」でもいろいろと見つかると思います。

**Comment by renangton** [comment]
完了
